name: Users App Deployment
on:
  push:
    branches: main
env:
  BACKEND_URL: ${{ secrets.BACKEND_URL }}
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: get codes
        uses: actions/checkout@v4
      - name: install node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: npm install
      - name: deploy the app
        run: |
          echo "app deploying......"
